version: '3'
networks:
  web:
services:
  mysql:
    image: mysql:5.7
    volumes:
      - C:\data\_mysql:/var/lib/mysql
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance
    ports:
      - 3306:3306
